-- MySQL Script generated by MySQL Workbench
-- Mon Sep  1 16:08:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único de la persona',
  `nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre completo de la persona',
  `correo_electronico` VARCHAR(100) NOT NULL COMMENT 'Correo electrónico de la persona',
  `usuario` VARCHAR(45) NOT NULL COMMENT 'Nombre de usuario para acceso',
  `contrasena` VARCHAR(255) NOT NULL COMMENT 'Contraseña encriptada del usuario',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de registro',
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de última actualización',
  `activo` TINYINT NOT NULL DEFAULT TRUE COMMENT 'Indica si la persona está activa',
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `idx_usuario_unico` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `idx_correo_unico` (`correo_electronico` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Personas registradas en el sistema';


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del producto',
  `nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre del producto financiero (ej. Tarjeta Visa, Préstamo personal)',
  `monto_maximo` DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Monto máximo permitido',
  `monto_minimo` DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Monto mínimo permitido',
  `porcentaje_interes` DECIMAL(5,2) NULL DEFAULT NULL COMMENT 'Porcentaje de interés aplicado',
  `tipo_producto` ENUM('TARJETA', 'PRESTAMO', 'OTRO') NOT NULL DEFAULT 'OTRO' COMMENT 'Tipo de producto financiero',
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `idx_nombre_producto_unico` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Productos financieros (tarjeta, préstamo, etc.)';


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
COMMENT = 'Categorías de movimientos financieros';


-- -----------------------------------------------------
-- Table `mydb`.`beneficiario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`beneficiario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`beneficiario` (
  `id_beneficiario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_beneficiario`))
ENGINE = InnoDB
COMMENT = 'Beneficiarios de movimientos o transacciones';


-- -----------------------------------------------------
-- Table `mydb`.`movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movimiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movimiento` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Código de referencia del movimiento',
  `monto` DECIMAL(15,2) NOT NULL COMMENT 'Monto del movimiento',
  `tipo` ENUM('CARGO', 'ABONO') NOT NULL COMMENT 'Tipo de movimiento',
  `cuotas` INT NULL DEFAULT NULL COMMENT 'Cantidad de cuotas si aplica',
  `estado` ENUM('PENDIENTE', 'PAGADO', 'CANCELADO') NULL DEFAULT 'PENDIENTE' COMMENT 'Estado del movimiento',
  `id_producto` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_beneficiario` INT NOT NULL,
  PRIMARY KEY (`id_movimiento`),
  INDEX `idx_mov_producto_persona` (`id_producto` ASC, `id_persona` ASC) VISIBLE,
  INDEX `fk_mov_persona` (`id_persona` ASC) VISIBLE,
  INDEX `fk_mov_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_mov_beneficiario` (`id_beneficiario` ASC) VISIBLE,
  CONSTRAINT `fk_mov_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id_producto`),
  CONSTRAINT `fk_mov_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `mydb`.`persona` (`id_persona`),
  CONSTRAINT `fk_mov_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`),
  CONSTRAINT `fk_mov_beneficiario`
    FOREIGN KEY (`id_beneficiario`)
    REFERENCES `mydb`.`beneficiario` (`id_beneficiario`))
ENGINE = InnoDB
COMMENT = 'Movimientos financieros asociados a productos';


-- -----------------------------------------------------
-- Table `mydb`.`transaccion_programada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transaccion_programada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transaccion_programada` (
  `id_transaccion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tipo` ENUM('CARGO', 'ABONO') NOT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `frecuencia` ENUM('DIARIA', 'SEMANAL', 'MENSUAL', 'ANUAL') NOT NULL COMMENT 'Frecuencia de repetición',
  `repeticion` INT NULL DEFAULT NULL COMMENT 'Número de repeticiones',
  `id_categoria` INT NOT NULL,
  `id_beneficiario` INT NOT NULL,
  PRIMARY KEY (`id_transaccion`),
  INDEX `fk_tp_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_tp_beneficiario` (`id_beneficiario` ASC) VISIBLE,
  CONSTRAINT `fk_tp_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`),
  CONSTRAINT `fk_tp_beneficiario`
    FOREIGN KEY (`id_beneficiario`)
    REFERENCES `mydb`.`beneficiario` (`id_beneficiario`))
ENGINE = InnoDB
COMMENT = 'Transacciones programadas';


-- -----------------------------------------------------
-- Table `mydb`.`prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prestamo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prestamo` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `estado` ENUM('ACTIVO', 'CANCELADO', 'MORA') NOT NULL,
  `moneda` VARCHAR(10) NOT NULL,
  `saldo_inicial` DECIMAL(15,2) NOT NULL,
  `limite_credito` DECIMAL(15,2) NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  INDEX `fk_prestamo_persona` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `mydb`.`persona` (`id_persona`))
ENGINE = InnoDB
COMMENT = 'Préstamos asociados a personas';


-- -----------------------------------------------------
-- Table `mydb`.`activo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`activo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`activo` (
  `id_activo` INT NOT NULL AUTO_INCREMENT,
  `nombre_activo` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(15,2) NOT NULL,
  `depreciacion` DECIMAL(15,2) NULL DEFAULT NULL,
  `id_persona` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_activo`),
  INDEX `fk_activo_persona` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_activo_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `mydb`.`persona` (`id_persona`))
ENGINE = InnoDB
COMMENT = 'Activos de las personas';


-- -----------------------------------------------------
-- Table `mydb`.`presupuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`presupuesto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`presupuesto` (
  `id_presupuesto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `monto_total` DECIMAL(15,2) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_presupuesto`),
  INDEX `fk_presupuesto_persona` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_presupuesto_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `mydb`.`persona` (`id_persona`))
ENGINE = InnoDB
COMMENT = 'Presupuestos definidos por los usuarios';


-- -----------------------------------------------------
-- Table `mydb`.`tarjeta_credito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tarjeta_credito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tarjeta_credito` (
  `id_tarjeta` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único de la tarjeta de crédito',
  `id_producto` INT NOT NULL COMMENT 'Referencia al producto',
  `numero_tarjeta` VARCHAR(20) NOT NULL COMMENT 'Número de la tarjeta',
  `limite_credito` DECIMAL(15,2) NOT NULL COMMENT 'Límite de crédito de la tarjeta',
  `saldo_actual` DECIMAL(15,2) NOT NULL COMMENT 'Saldo actual de la tarjeta',
  `fecha_corte` DATE NOT NULL COMMENT 'Fecha de corte de la tarjeta',
  `fecha_pago` DATE NOT NULL COMMENT 'Fecha límite de pago',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de registro de la tarjeta',
  `estado` ENUM('ACTIVA', 'INACTIVA', 'CANCELADA') NOT NULL DEFAULT 'ACTIVA' COMMENT 'Estado de la tarjeta',
  PRIMARY KEY (`id_tarjeta`),
  INDEX `fk_tc_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_tc_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id_producto`))
ENGINE = InnoDB
COMMENT = 'Tarjetas de crédito asociadas a productos';


-- -----------------------------------------------------
-- Table `mydb`.`pago_tarjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pago_tarjeta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pago_tarjeta` (
  `id_pago` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del pago',
  `id_tarjeta` INT NOT NULL COMMENT 'Referencia a la tarjeta de crédito',
  `fecha_pago` DATE NOT NULL COMMENT 'Fecha del pago',
  `monto_pago` DECIMAL(15,2) NOT NULL COMMENT 'Monto pagado',
  `referencia` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Referencia o descripción del pago',
  `id_persona` INT NULL DEFAULT NULL COMMENT 'Persona que realizó el pago',
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pt_tarjeta` (`id_tarjeta` ASC) VISIBLE,
  INDEX `fk_pt_persona` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_pt_tarjeta`
    FOREIGN KEY (`id_tarjeta`)
    REFERENCES `mydb`.`tarjeta_credito` (`id_tarjeta`),
  CONSTRAINT `fk_pt_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `mydb`.`persona` (`id_persona`))
ENGINE = InnoDB
COMMENT = 'Pagos realizados a tarjetas de crédito';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
