-- MySQL Script generated by MySQL Workbench
-- Sun Aug 31 23:33:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idproducto` INT NOT NULL,
  `nombre del producto` VARCHAR(45) NULL,
  `monto maxio` VARCHAR(45) NULL,
  `monto minimo` VARCHAR(45) NULL,
  `porcentaje de interes` VARCHAR(45) NULL,
  `idproductocol` VARCHAR(45) NULL,
  `productocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproducto`, `productocol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `idpersona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_has_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto_has_persona` (
  `producto_idproducto` INT NOT NULL,
  `producto_productocol` VARCHAR(45) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`producto_idproducto`, `producto_productocol`, `persona_idpersona`),
  INDEX `fk_producto_has_persona_persona1_idx` (`persona_idpersona` ASC) VISIBLE,
  INDEX `fk_producto_has_persona_producto_idx` (`producto_idproducto` ASC, `producto_productocol` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_persona_producto`
    FOREIGN KEY (`producto_idproducto` , `producto_productocol`)
    REFERENCES `mydb`.`producto` (`idproducto` , `productocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_persona_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `mydb`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimientos` (
  `id movimiento` INT NOT NULL,
  `codigo movimiento` VARCHAR(45) NULL,
  `beneficiario` VARCHAR(45) NULL,
  `cageoria` VARCHAR(45) NULL,
  `monto` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `producto_has_persona_producto_idproducto` INT NOT NULL,
  `producto_has_persona_producto_productocol` VARCHAR(45) NOT NULL,
  `producto_has_persona_persona_idpersona` INT NOT NULL,
  `category_category_id` INT NOT NULL,
  `coutas` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id movimiento`, `producto_has_persona_producto_idproducto`, `producto_has_persona_producto_productocol`, `producto_has_persona_persona_idpersona`, `category_category_id`),
  INDEX `fk_movimientos_producto_has_persona1_idx` (`producto_has_persona_producto_idproducto` ASC, `producto_has_persona_producto_productocol` ASC, `producto_has_persona_persona_idpersona` ASC) VISIBLE,
  INDEX `fk_movimientos_category1_idx` (`category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_movimientos_producto_has_persona1`
    FOREIGN KEY (`producto_has_persona_producto_idproducto` , `producto_has_persona_producto_productocol` , `producto_has_persona_persona_idpersona`)
    REFERENCES `mydb`.`producto_has_persona` (`producto_idproducto` , `producto_productocol` , `persona_idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`beneficiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`beneficiario` (
  `idbeneficiario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
